USE ApressFinancial
GO

SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET CONCAT_NULL_YIELDS_NULL ON
SET ARITHABORT ON
SET QUOTED_IDENTIFIER ON
SET NUMERIC_ROUNDABORT OFF
GO

CREATE UNIQUE CLUSTERED INDEX IX_CustFinProds
ON CustomerDetails.v_CustFinProducts (CustomerId, ProductName)
GO

SET ANSI_NULLS OFF
SET ANSI_PADDING OFF
SET ANSI_WARNINGS OFF
SET CONCAT_NULL_YIELDS_NULL OFF
SET ARITHABORT OFF
SET QUOTED_IDENTIFIER OFF
SET NUMERIC_ROUNDABORT ON
GO